### ISSUE TITLE
Version 0.0.3 ready to go?

### ISSUE THREAD

**Issue by JockLawrie** [jkaye2012/Redis.jl#18]
Hi there,

I'm using version 0.0.2 with Julia 0.4.1 and I'm getting lots of deprecation warnings which clutter up a log file for a script I run daily.

I see this problem has been [fixed](https://github.com/jkaye2012/Redis.jl/issues/15) for version 0.0.3, and that there are no outstanding issues for version 0.0.3. Does this mean that version 0.0.3 is ready to go?
It'd be great to eliminate the deprecation warnings from the log file.

Cheers,
Jock

**Comment by jkaye2012** [comment]
Hi Jock.

When running the regression tests, I found that nb_available(::TCPSocket) was always returning 0 within the subscription loop, regardless of whether or not data was actually available on the socket (I could tell that data was there because changing it to a blocking read caused the simple case to work, but the blocking read has other problems as detailed [here](https://github.com/jkaye2012/Redis.jl/blob/master/src/client.jl#L47)).

I've been on the IRC a number of times attempting to determine if this is just an issue with my machine or an issue in general. Are you able to run the regression tests on head of origin/master and have everything pass? As long as we can verify that there is not a regression, I think that v0.0.3 is good to go.

--Jordan

**Comment by JockLawrie** [comment]
Hi Jordan,

I ran test/redis_tests.jl using Julia 0.4.1 and origin/master of Redis.jl.
I'm using Debian Jessie.
I get a failure only on the last test, on line 50...``x`` remains equal to ``Any[]``.
As you have noted, this is indeed because nb_available always returns 0 (I tested this with a print statement).
I'm afraid I can't be of much help because this problem is outside my skill set.
Let me know if you'd like me to run further tests though.

Jock

**Comment by jkaye2012** [comment]
After more investigation and no answer, I've opened [this issue](https://github.com/JuliaLang/julia/issues/14269) in hopes of getting this resolved. I'll update with any further information as I get it.

--Jordan

**Comment by JockLawrie** [comment]
Great, thanks.

**Comment by jkaye2012** [comment]
I've just tagged v0.1.0.

Cheers,
Jordan
