### ISSUE TITLE
Create a big random list

### ISSUE THREAD

**Issue by NaelsonDouglas** [jkaye2012/Redis.jl#25]
Hello,

I'm trying to create a big list with
lpush(conn, "list", rand(1000000))

It took +-2 hours and the list wasn't created (the console freezes). The same doesn't happen with lower values, like 500k.

Can you give-me some advice about this? Is that a problem in Julia, Redis.jl or in my approach?

Thanks.

**Comment by jkaye2012** [comment]
Hello again,

There are a couple of ways to speed this up. The first (most straightforward) is just to push the elements on one at a time, like so:

```julia
r = RedisConnection()
@time for i in rand(1000000)
    lpush(r, :list, i)
end
 81.743994 seconds (127.32 M allocations: 5.405 GB, 0.66% gc time)
```

We can get even better performance by using a pipeline since it seems that you aren't concerned with reading in the middle:

```julia
p = open_pipeline(r)
@time for i in rand(1000000)
    lpush(p, :list, i)
end
 32.552696 seconds (107.32 M allocations: 4.704 GB, 1.49% gc time)
```

Would either of these work for you?

--Jordan

**Comment by NaelsonDouglas** [comment]
Thank you for your answer!

We are actually using the loop approach (
for i=1:2) 
lpush(r,list,rand(500000))
..

and it's working fine, the issue was only to to clear the question if that was a flaw in the code or anything like that.

I'm closing the issue since it's cleared the loop approach is good enough.

Thanks.
